version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache: # can remove the cache step and just run npm run lint
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:   # can remove the cache step and just run npm run test
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:  # can remove the cache step and just run npm audit
          keys:
            - "npm-packages"
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
